### ISSUE TITLE
register Artefact_types

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3370] opened 2024-02-22 19:23 UTC
I am playing with the database to get to a productive state, i.e. without test data but with necessary base data included. I therefore removed all entries from the `filepath_type`.

When starting the qtp-sequencing plugin, qiita complains about invalid data in table filepath_type:

```
(qtp-sequencing) qiita@vbox-stefan:~/Git/qiita-spots/qiita/qiita_core/support_files$ start_qtp_sequencing https://localhost:8383 register ignored
/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/qiita_files/util.py:15: H5pyDeprecationWarning: h5py.get_config().default_file_mode is deprecated. The default mode is now always 'r' (read-only).
  if hasattr(h5py.get_config(), 'default_file_mode'):
/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/qiita_files/util.py:16: H5pyDeprecationWarning: Setting h5py.default_file_mode is deprecated. 'r' (read-only) is the default from h5py 3.0.
  h5py.get_config().default_file_mode = 'r'
Traceback (most recent call last):
  File "/home/qiita/miniforge3/envs/qtp-sequencing/bin/start_qtp_sequencing", line 26, in <module>
    execute()
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/bin/start_qtp_sequencing", line 22, in execute
    plugin(url, job_id, output_dir)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/qiita_client/plugin.py", line 251, in __call__
    self._register(qclient)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/qiita_client/plugin.py", line 345, in _register
    qclient.post('/qiita_db/artifacts/types/', data=data)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/qiita_client/qiita_client.py", line 411, in post
    return self._request_retry(self._session.post, url, **kwargs)
  File "/home/qiita/miniforge3/envs/qtp-sequencing/lib/python3.9/site-packages/qiita_client/qiita_client.py", line 360, in _request_retry
    raise RuntimeError(
RuntimeError: Request 'post https://localhost:8383/qiita_db/artifacts/types/' did not succeed. Status code: 500. Message: raw_sff not valid for table filepath_type
```
I wonder if this happens by design (because you want to have full control of filetypes) or this might be gap in the plugin registration code?

**Comment by antgonza** [comment] 2024-02-23 00:47
If I understand correctly the meaning of this: """I am playing with the database to get to a productive state""", I think what you are doing is that you had a TEST database and then you change the settings to make them "production", right?

If yes, I think the problem is that this will pre-populate the DB with TESTS entries and deleting/changing some of them directly in the DB will make the database inconsistent. 

My suggestion is to delete the full database and start with a production system from scratch, then create any new users, software, types, etc from scratch using the APIs vs. directly on the DB.

Hope this helps.

**Comment by sjanssen2** [comment] 2024-02-23 10:55
Your understanding is perfectly OK and I would 100% prefer a clean way to setup a new productive DB state. However I lack the knowledge on how to do that.
I thought, I had to 
  - set `TEST_ENVIRONMENT` in qiita's config file to `FALSE`: https://github.com/jlab/qiita/blob/d3def54a12c38f8bdccebd9143694aa4cd4040af/.github/workflows/qiita-ci.yml#L61
  - ensure no plugin configuration files are in the ~/.qiita_plugins (or whatever path is set) directory
  - and execute `qiita-env make` without the `--no-load-ontologies` flag https://github.com/jlab/qiita/blob/d3def54a12c38f8bdccebd9143694aa4cd4040af/.github/workflows/qiita-ci.yml#L143

Am I missing steps here?
I've changed the github action workflow to demonstrate what I am doing: https://github.com/qiita-spots/qiita/pull/3373
But you can see from the output, that the database still contains e.g. three softwares https://github.com/qiita-spots/qiita/actions/runs/8018011498/job/21903022490?pr=3373#step:8:187 and workflows https://github.com/qiita-spots/qiita/actions/runs/8018011498/job/21903022490?pr=3373#step:8:193

**Comment by antgonza** [comment] 2024-02-23 22:31
What I meant is that you should delete the database via SQL and then create it via the qiita commands. Now the ontologies are quite old and not really used internally but AFAIK they should probably load correctly.

I think this and [this other issue](https://github.com/qiita-spots/qiita/issues/3372) are related.

**Comment by antgonza** [comment] 2024-05-15 13:19
Closing this because:
- the production database (in the dev branch) is now completely empty
- this issue has been superseded by https://github.com/qiita-spots/qiita/issues/3374.

**Closed by antgonza** 2024-05-15 13:19 UTC
