### ISSUE TITLE
per_sample_FAST validator does not allow empty files after filtering

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qiita#3187] opened 2022-03-05 01:33 UTC
See the iSeq prep of [13309](https://qiita.ucsd.edu/study/description/13309#)

**Comment by antgonza** [comment] 2022-03-15 13:24
@wasade, thank you for reporting. I updated the title to reflect what's actually happening, the artifact validator expects that all samples to have a file and [that the file is over 100 in size](https://github.com/qiita-spots/qtp-sequencing/blob/master/qtp_sequencing/validate.py#L328). Note that we have a similar comparison in the sequence processing pipeline to avoid moving/using files that are too small for processing. 

IMOO this is a feature and not a bug 😉 as this way we don't store small files that will not produce any value.

Now, this is an extreme case, as you know, because most sequences do not match anything so even larger files do not produce anything. So I think we could either:
1. Do nothing, and basically have users delete those empty files by hand - which is what I just did.
2. Increment the validator minimal range from 100 to 2000, see [*]

What do you think?

[*]
```bash
(qiita) 06:08:00 (qiita@qiita):143249$ ls --sort=size -l *.fastp.fastq.gz | tail
-rw-rw-r--+ 1 qiita qiita    1296 Mar  4 12:46 0363148442_S251_L001_R2_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita    1217 Mar  4 12:46 0363148442_S251_L001_R1_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita    1061 Mar  4 12:47 BLANK6_6A_S137_L001_R2_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita    1014 Mar  4 12:47 BLANK6_6A_S137_L001_R1_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita    1010 Mar  4 12:47 BLANK5_5A_S33_L001_R2_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita     930 Mar  4 12:47 BLANK5_5A_S33_L001_R1_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita     763 Mar  4 12:47 BLANK6_6G_S143_L001_R2_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita     703 Mar  4 12:47 BLANK6_6G_S143_L001_R1_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita     670 Mar  4 12:46 0363237586_S146_L001_R2_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita     617 Mar  4 12:46 0363237586_S146_L001_R1_001.fastp.fastq.gz
(qiita) 06:08:05 (qiita@qiita):143249$ ls --sort=size -l 0363237630_S157_L001_R*.fastp.fastq.gz 
-rw-rw-r--+ 1 qiita qiita 2047 Mar  4 12:46 0363237630_S157_L001_R2_001.fastp.fastq.gz
-rw-rw-r--+ 1 qiita qiita 1928 Mar  4 12:46 0363237630_S157_L001_R1_001.fastp.fastq.gz
```

**Comment by wasade** [comment] 2022-03-15 21:05
I don't believe this is an exceptional scenario as we expect some samples to drop out with low depth runs like with the iSeq. A failure here would require human intervention from the wet lab as well which would present a delay in processing.

**Comment by antgonza** [comment] 2022-04-15 17:26
After internal discussion we decided to go with a min size of 3.1K for our internal pipeline: https://github.com/biocore/mg-scripts/pull/73. Closing.

**Closed by antgonza** 2022-04-15 17:26 UTC
