### ISSUE TITLE
Make it easier for Qiita admins to help users: forum and added text next to qiita help email

### ISSUE THREAD

**Issue by stephanieorch** [qiita-spots/qiita#2652] opened 2018-08-29 16:19 UTC
1. Create a forum so that it's easier to figure out who to send the issues to as well as have users add the required information. The forum will contain the necessary information to help admins answer questions (ex. study/analysis ID, screenshots, etc.). Then the forum would send the issue to both the qiita help email (and maybe also to the qiita admin that would best answer the question). 

2. With "Questions? qiita.help@gmail.com" add "Add your sample/analysis ID with your issues" so people know what to add to their forum/email.

**Comment by adswafford** [comment] 2018-10-01 15:42
It looks like the text is fixed, but how easy would it be to stand up a forum using a similar to Qiime2, perhaps using the same base: https://github.com/discourse/discourse ?

**Comment by antgonza** [comment] 2018-10-01 15:48
We could do something like that or use literally the same backbone than Qiime2 but the issue is that normally we are dealing with private studies ... so not sure if it will be better to have something internal ...

**Comment by antgonza** [comment] 2020-06-26 19:41
@adswafford, do you think this is still relevant?

**Comment by adswafford** [comment] 2020-06-27 01:18
I think so if we want to try to grow the Qiita 'community'; since Qiita's backbone is Q2, would it make sense to just have a Qiita section on their forum to make it as easy to handle as we can?

**Comment by antgonza** [comment] 2020-11-17 22:17
@adswafford, chatted with the Q2 devs and they think it would be beneficial for both projects (Qiita and QIIME 2) to maintain separate user support forums and suggested creating our own as is not expensive ($458.00 up front for a 36 month) and low maintenance; they also offered help to set it up. 

Now, based on the amount of question we get (~1-2 per week vs. the number of new users and studies we get: ~1.5K users and ~350 studies per year) and our current formula of adding documentation for common questions; I don't think is worth creating our own. What do you think?

**Comment by adswafford** [comment] 2020-11-18 00:39
I think having our own makes sense, and although the number of help account
questions is low, my impression is that there is still a lot of reluctance
to use Qiita, even for folks at UCSD, due to insufficient help
troubleshooting. Based on the popularity of the Q2 forum, I'm optimistic
that having a similar venue will foster additional usage, more organic
development of tutorials/FAQs and more insight into user issues as they
relate to feature requests and bugs.

Ny preference would be to try it out, and then if it isn't heavily used, we
can not renew in 3 years?

**Comment by antgonza** [comment] 2021-05-12 18:19
After multiple iterations and due to the improved documentation, it seems like a forum is no longer a requirement. However, we should continue improving the text in the documents and the tutorials. Anyway, closing this issue.

**Closed by antgonza** 2021-05-12 18:19 UTC
Labels: GUI, enhancement, group input, nice-to-have

**Comment by adswafford** [comment] 2021-05-12 20:13
Seems okay to close for now, but still think the forum would be a useful
addition at some point to get a better sense and foster the user community.
